export const LOADS_DATA = [
  { loadId: "LD-1001", origin: "Chicago, IL", destination: "Dallas, TX", pickupDatetime: new Date("2026-04-10T08:00:00Z"), deliveryDatetime: new Date("2026-04-11T18:00:00Z"), equipmentType: "Dry Van", loadboardRate: 2850, notes: "No-touch freight. Dock-to-dock delivery.", weight: 38000, commodityType: "Consumer Electronics", numOfPieces: 24, miles: 920, dimensions: "48x40x48 pallets" },
  { loadId: "LD-1002", origin: "Atlanta, GA", destination: "Miami, FL", pickupDatetime: new Date("2026-04-10T06:00:00Z"), deliveryDatetime: new Date("2026-04-11T12:00:00Z"), equipmentType: "Reefer", loadboardRate: 2200, notes: "Temperature must stay between 34-38°F. USDA seal required.", weight: 42000, commodityType: "Fresh Produce", numOfPieces: 20, miles: 660, dimensions: "48x40x60 pallets" },
  { loadId: "LD-1003", origin: "Los Angeles, CA", destination: "Phoenix, AZ", pickupDatetime: new Date("2026-04-11T10:00:00Z"), deliveryDatetime: new Date("2026-04-12T08:00:00Z"), equipmentType: "Flatbed", loadboardRate: 1800, notes: "Tarps required. Oversize load - wide load permit needed.", weight: 44000, commodityType: "Steel Beams", numOfPieces: 6, miles: 370, dimensions: "40ft x 8ft" },
  { loadId: "LD-1004", origin: "Houston, TX", destination: "New Orleans, LA", pickupDatetime: new Date("2026-04-10T14:00:00Z"), deliveryDatetime: new Date("2026-04-11T10:00:00Z"), equipmentType: "Dry Van", loadboardRate: 1450, notes: "Liftgate required at delivery. Appointment needed.", weight: 28000, commodityType: "Packaged Food", numOfPieces: 30, miles: 350, dimensions: "48x40x48 pallets" },
  { loadId: "LD-1005", origin: "Nashville, TN", destination: "Charlotte, NC", pickupDatetime: new Date("2026-04-12T07:00:00Z"), deliveryDatetime: new Date("2026-04-13T06:00:00Z"), equipmentType: "Dry Van", loadboardRate: 1650, notes: "Driver assist unload. 2-stop delivery.", weight: 32000, commodityType: "Automotive Parts", numOfPieces: 18, miles: 410, dimensions: "Standard pallets" },
  { loadId: "LD-1006", origin: "Denver, CO", destination: "Salt Lake City, UT", pickupDatetime: new Date("2026-04-11T09:00:00Z"), deliveryDatetime: new Date("2026-04-12T14:00:00Z"), equipmentType: "Reefer", loadboardRate: 1950, notes: "Frozen goods -10°F. Team drivers preferred.", weight: 40000, commodityType: "Frozen Seafood", numOfPieces: 22, miles: 525, dimensions: "48x40x48 pallets" },
  { loadId: "LD-1007", origin: "Seattle, WA", destination: "Portland, OR", pickupDatetime: new Date("2026-04-10T11:00:00Z"), deliveryDatetime: new Date("2026-04-10T20:00:00Z"), equipmentType: "Box Truck", loadboardRate: 750, notes: "Last-mile delivery. White glove service.", weight: 8000, commodityType: "Furniture", numOfPieces: 45, miles: 175, dimensions: "Mixed sizes" },
  { loadId: "LD-1008", origin: "Detroit, MI", destination: "Indianapolis, IN", pickupDatetime: new Date("2026-04-13T06:00:00Z"), deliveryDatetime: new Date("2026-04-13T18:00:00Z"), equipmentType: "Step Deck", loadboardRate: 1350, notes: "Heavy machinery. Chains and binders required.", weight: 35000, commodityType: "Industrial Equipment", numOfPieces: 3, miles: 280, dimensions: "12ft x 8ft x 7ft per unit" },
  { loadId: "LD-1009", origin: "New York, NY", destination: "Boston, MA", pickupDatetime: new Date("2026-04-11T05:00:00Z"), deliveryDatetime: new Date("2026-04-11T16:00:00Z"), equipmentType: "Dry Van", loadboardRate: 1100, notes: "HAZMAT class 3. Placard required.", weight: 25000, commodityType: "Chemical Products", numOfPieces: 50, miles: 215, dimensions: "55-gallon drums" },
  { loadId: "LD-1010", origin: "Memphis, TN", destination: "St. Louis, MO", pickupDatetime: new Date("2026-04-12T08:00:00Z"), deliveryDatetime: new Date("2026-04-12T20:00:00Z"), equipmentType: "Dry Van", loadboardRate: 980, notes: "Drop trailer available. FCFS pickup.", weight: 35000, commodityType: "Paper Products", numOfPieces: 28, miles: 285, dimensions: "48x40x48 pallets" },
  { loadId: "LD-1011", origin: "San Francisco, CA", destination: "Las Vegas, NV", pickupDatetime: new Date("2026-04-14T07:00:00Z"), deliveryDatetime: new Date("2026-04-15T08:00:00Z"), equipmentType: "Dry Van", loadboardRate: 1700, notes: "High-value goods. Seal required at origin.", weight: 30000, commodityType: "Wine & Spirits", numOfPieces: 40, miles: 570, dimensions: "48x40x48 pallets" },
  { loadId: "LD-1012", origin: "Kansas City, MO", destination: "Omaha, NE", pickupDatetime: new Date("2026-04-10T12:00:00Z"), deliveryDatetime: new Date("2026-04-11T06:00:00Z"), equipmentType: "Flatbed", loadboardRate: 850, notes: "Lumber load. Straps and edge protectors required.", weight: 45000, commodityType: "Lumber", numOfPieces: 1, miles: 190, dimensions: "Various lengths up to 20ft" },
] as const;

type Outcome = "booked" | "declined" | "no_loads" | "carrier_not_eligible" | "negotiation_failed" | "transferred" | "callback_requested" | "dropped";
type Sentiment = "positive" | "neutral" | "negative" | "frustrated";

export const SAMPLE_CALLS_DATA: {
  callId: string;
  carrierMcNumber: string;
  carrierName: string;
  callerName: string;
  originRequested: string;
  destinationRequested: string;
  equipmentRequested: string;
  loadboardRate: number | null;
  initialOffer: number | null;
  finalAgreedRate: number | null;
  counterOffers: { round: number; carrier: number; broker: number | null }[];
  negotiationRounds: number;
  outcome: Outcome;
  sentiment: Sentiment;
  callDurationSeconds: number;
  notes: string;
  transcriptSummary: string;
  extractedData: Record<string, unknown>;
}[] = [
  { callId: "CALL-2001", carrierMcNumber: "784569", carrierName: "Swift Logistics LLC", callerName: "Mike Thompson", originRequested: "Chicago, IL", destinationRequested: "Dallas, TX", equipmentRequested: "Dry Van", loadboardRate: 2850, initialOffer: 2600, finalAgreedRate: 2750, counterOffers: [{ round: 1, carrier: 2600, broker: 2800 }, { round: 2, carrier: 2750, broker: 2750 }], negotiationRounds: 2, outcome: "booked", sentiment: "positive", callDurationSeconds: 245, notes: "Carrier accepted after 2 rounds.", transcriptSummary: "Carrier called for Chicago-Dallas dry van. Booked.", extractedData: { driver_name: "John P.", truck_number: "TR-4421" } },
  { callId: "CALL-2002", carrierMcNumber: "332211", carrierName: "Blue Ridge Transport", callerName: "Sarah Kim", originRequested: "Atlanta, GA", destinationRequested: "Miami, FL", equipmentRequested: "Reefer", loadboardRate: 2200, initialOffer: 1800, finalAgreedRate: null, counterOffers: [{ round: 1, carrier: 1800, broker: 2134 }, { round: 2, carrier: 1900, broker: 2068 }, { round: 3, carrier: 1950, broker: null }], negotiationRounds: 3, outcome: "negotiation_failed", sentiment: "frustrated", callDurationSeconds: 380, notes: "Could not reach agreement.", transcriptSummary: "3 rounds failed.", extractedData: { reason: "Rate too low" } },
  { callId: "CALL-2003", carrierMcNumber: "556677", carrierName: "Heartland Carriers Inc", callerName: "Dave Russo", originRequested: "Denver, CO", destinationRequested: "Salt Lake City, UT", equipmentRequested: "Reefer", loadboardRate: 1950, initialOffer: 1950, finalAgreedRate: 1950, counterOffers: [], negotiationRounds: 0, outcome: "booked", sentiment: "positive", callDurationSeconds: 142, notes: "Accepted immediately.", transcriptSummary: "Quick booking.", extractedData: { driver_name: "Pete M." } },
  { callId: "CALL-2004", carrierMcNumber: "999888", carrierName: "Unknown Carrier", callerName: "Unknown", originRequested: "Los Angeles, CA", destinationRequested: "Phoenix, AZ", equipmentRequested: "Flatbed", loadboardRate: null, initialOffer: null, finalAgreedRate: null, counterOffers: [], negotiationRounds: 0, outcome: "carrier_not_eligible", sentiment: "neutral", callDurationSeconds: 65, notes: "MC not found.", transcriptSummary: "Verification failed.", extractedData: {} },
  { callId: "CALL-2005", carrierMcNumber: "445566", carrierName: "Pacific Freight Solutions", callerName: "Linda Chen", originRequested: "Seattle, WA", destinationRequested: "Portland, OR", equipmentRequested: "Box Truck", loadboardRate: 750, initialOffer: 700, finalAgreedRate: 720, counterOffers: [{ round: 1, carrier: 700, broker: 728 }], negotiationRounds: 1, outcome: "transferred", sentiment: "positive", callDurationSeconds: 195, notes: "Transferred to rep.", transcriptSummary: "Negotiated to $720.", extractedData: { driver_name: "Linda C." } },
  { callId: "CALL-2006", carrierMcNumber: "112233", carrierName: "Midwest Express LLC", callerName: "Tom Jackson", originRequested: "Memphis, TN", destinationRequested: "St. Louis, MO", equipmentRequested: "Dry Van", loadboardRate: 980, initialOffer: 980, finalAgreedRate: 980, counterOffers: [], negotiationRounds: 0, outcome: "booked", sentiment: "positive", callDurationSeconds: 118, notes: "Accepted immediately.", transcriptSummary: "Fast booking.", extractedData: { driver_name: "Tom J." } },
  { callId: "CALL-2007", carrierMcNumber: "778899", carrierName: "East Coast Haulers", callerName: "Maria Santos", originRequested: "New York, NY", destinationRequested: "Philadelphia, PA", equipmentRequested: "Dry Van", loadboardRate: null, initialOffer: null, finalAgreedRate: null, counterOffers: [], negotiationRounds: 0, outcome: "no_loads", sentiment: "neutral", callDurationSeconds: 90, notes: "No matching loads.", transcriptSummary: "No loads found.", extractedData: {} },
  { callId: "CALL-2008", carrierMcNumber: "654321", carrierName: "Southern Freight Co", callerName: "Bobby Williams", originRequested: "Houston, TX", destinationRequested: "New Orleans, LA", equipmentRequested: "Dry Van", loadboardRate: 1450, initialOffer: 1300, finalAgreedRate: 1380, counterOffers: [{ round: 1, carrier: 1300, broker: 1407 }, { round: 2, carrier: 1380, broker: 1380 }], negotiationRounds: 2, outcome: "booked", sentiment: "neutral", callDurationSeconds: 310, notes: "Agreed at $1380.", transcriptSummary: "Booked.", extractedData: { driver_name: "Bobby W." } },
  { callId: "CALL-2009", carrierMcNumber: "887766", carrierName: "Rocky Mountain Trucking", callerName: "Jim Baker", originRequested: "Nashville, TN", destinationRequested: "Charlotte, NC", equipmentRequested: "Dry Van", loadboardRate: 1650, initialOffer: 1500, finalAgreedRate: null, counterOffers: [{ round: 1, carrier: 1500, broker: 1601 }], negotiationRounds: 1, outcome: "declined", sentiment: "negative", callDurationSeconds: 175, notes: "Carrier declined.", transcriptSummary: "Declined.", extractedData: {} },
  { callId: "CALL-2010", carrierMcNumber: "334455", carrierName: "Great Plains Logistics", callerName: "Amy Rodriguez", originRequested: "Kansas City, MO", destinationRequested: "Omaha, NE", equipmentRequested: "Flatbed", loadboardRate: 850, initialOffer: 850, finalAgreedRate: 850, counterOffers: [], negotiationRounds: 0, outcome: "transferred", sentiment: "positive", callDurationSeconds: 130, notes: "Transferred.", transcriptSummary: "Accepted rate.", extractedData: { driver_name: "Amy R." } },
  { callId: "CALL-2011", carrierMcNumber: "556677", carrierName: "Heartland Carriers Inc", callerName: "Dave Russo", originRequested: "San Francisco, CA", destinationRequested: "Las Vegas, NV", equipmentRequested: "Dry Van", loadboardRate: 1700, initialOffer: 1550, finalAgreedRate: 1649, counterOffers: [{ round: 1, carrier: 1550, broker: 1649 }, { round: 2, carrier: 1649, broker: 1649 }], negotiationRounds: 2, outcome: "booked", sentiment: "positive", callDurationSeconds: 220, notes: "Returning carrier.", transcriptSummary: "Booked.", extractedData: { returning_carrier: true } },
  { callId: "CALL-2012", carrierMcNumber: "221133", carrierName: "Gulf Coast Shipping", callerName: "Ray Nguyen", originRequested: "Chicago, IL", destinationRequested: "Dallas, TX", equipmentRequested: "Dry Van", loadboardRate: 2850, initialOffer: 2400, finalAgreedRate: null, counterOffers: [{ round: 1, carrier: 2400, broker: 2765 }, { round: 2, carrier: 2500, broker: 2679 }, { round: 3, carrier: 2550, broker: null }], negotiationRounds: 3, outcome: "negotiation_failed", sentiment: "frustrated", callDurationSeconds: 420, notes: "Failed after 3 rounds.", transcriptSummary: "Negotiation failed.", extractedData: {} },
];
